# Generated by Django 3.0.5 on 2020-12-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='images/profile/1.jpg', upload_to='images/profile/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='summary',
            field=models.CharField(default='This is your summary! Write something about yourself!', max_length=200),
        ),
    ]
