# Generated by Django 3.0.3 on 2020-10-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='test', unique=True),
            preserve_default=False,
        ),
    ]
