# Generated by Django 3.1.4 on 2020-12-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
