# Generated by Django 3.0.3 on 2020-10-17 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals_app', '0002_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
