# Generated by Django 3.0.5 on 2020-10-18 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals_app', '0005_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='downVote',
            new_name='vote',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='upVote',
        ),
    ]
