# Generated by Django 3.0.5 on 2020-10-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals_app', '0007_auto_20201021_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vote_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
