# Generated by Django 3.0.5 on 2020-10-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals_app', '0008_post_vote_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='vote_score',
            field=models.IntegerField(default=0),
        ),
    ]
