# Generated by Django 3.0.5 on 2020-10-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals_app', '0009_auto_20201024_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='staff_picked',
            field=models.BooleanField(default=False),
        ),
    ]
