# Generated by Django 3.0.5 on 2020-12-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals_app', '0010_post_staff_picked'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lat',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='lng',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
