# Generated by Django 3.0.5 on 2020-12-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals_app', '0012_auto_20201209_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address_line_1',
            field=models.CharField(default='aaa', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='address_line_2',
            field=models.CharField(default='aaaa', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='postcode',
            field=models.IntegerField(default=2400),
            preserve_default=False,
        ),
    ]
