# Generated by Django 3.0.5 on 2020-12-11 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals_app', '0014_auto_20201211_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postcode',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='deals_app.Postcode'),
            preserve_default=False,
        ),
    ]
