# Generated by Django 3.1.4 on 2020-12-11 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals_app', '0015_post_postcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcode',
            old_name='region',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='post',
            name='postcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deals_app.postcode'),
        ),
    ]
